[kodama]
trees = "trees"
assets = "assets"
base-url = "/"

[toc]
placement = "right"
sticky = true
mobile-sticky = true
max-width = "45ex"

[text]
edit = "[edit]"
toc = "Table of Contents"
references = "References"
backlinks = "Backlinks"

[build]
typst-root = "trees"
short-slug = false
pretty-urls = false
footer-mode = "link"
inline-css = true
asref = false
output = "./docs"

[serve]
edit = "vscode://file/"
output = "./.cache/publish"
command = ["python", "-m", "http.server", "-d", "<output>"]

